Add release link to readme
JensvandeWiel/ArkAscendedServerManager pull request #114
Opened 2023-11-15 12:27 UTC by August2211

2023-11-15 12:59 UTC, JensvandeWiel requested changes
replace the link with this, it will install the latest on click 
https://github.com/JensvandeWiel/ArkAscendedServerManager/releases/download/latest/Ark-Ascended-Server-Manager-amd64-installer.exe

2023-11-16 07:48 UTC, August2211 commented
> replace the link with this, it will install the latest on click https://github.com/JensvandeWiel/ArkAscendedServerManager/releases/download/latest/Ark-Ascended-Server-Manager-amd64-installer.exe

![image](https://github.com/JensvandeWiel/ArkAscendedServerManager/assets/53059031/145ec955-2742-4a03-9257-06ce60c8436b)

Are you sure? :P

2023-11-16 07:53 UTC, August2211 commented
Used this link
https://github.com/JensvandeWiel/ArkAscendedServerManager/releases/latest/download/Ark-Ascended-Server-Manager-amd64-installer.exe

2023-11-16 09:18 UTC, JensvandeWiel approved these changes

2023-11-16 09:22 UTC, merged