Add command page, including DestroyWildDinos and SaveWorld
JensvandeWiel/ArkAscendedServerManager pull request #116
Opened 2023-11-16 20:25 UTC by jordandalby

This PR adds a command page, two commands have been added as of now:
- DestroyWildDinos
- SaveWorld

There is the possibility for expansion in the future. Though, additional commands may require an input box for args.

Closes #86

2023-11-17 08:56 UTC, JensvandeWiel requested changes
Looks great, only I think this list of commands should be under the console, and for #86  I don't think this is implemented here, that issue wants a dedicated wipe button, so you can wipe the server with one button and without manually needing to delete files.

2023-11-17 09:02 UTC, jordan-dalby commented
> Looks great, only I think this list of commands should be under the console, and for #86  I don't think this is implemented here, that issue wants a dedicated wipe button, so you can wipe the server with one button and without manually needing to delete files.

Ah I understand. I'll move them below the console and see about implementing the other feature in a different PR.

2023-11-18 11:54 UTC, jordan-dalby commented
Small change included, changed "clear input" to "clear console" to more accurately represent what the button does.

2023-11-21 14:23 UTC, JensvandeWiel approved these changes

2023-11-21 14:23 UTC, merged