80: Added button to open modal to show server startup command
JensvandeWiel/ArkAscendedServerManager pull request #81
Opened 2023-11-06 15:37 UTC by Ivan0348

2023-11-06 16:10 UTC, JensvandeWiel requested changes

2023-11-06 16:10 UTC, JensvandeWiel commented on frontend/src/pages/server/Administration.tsx
> +                                    GetServerWithError(serv.id, false).then(() => {
you are not actually using the retunred server, so you can remove GetServerWithError

2023-11-06 16:10 UTC, JensvandeWiel commented on server/server.go
> +		s.Command = s.GetServerCommand()
Rename to CreateServerCmd

2023-11-06 16:10 UTC, JensvandeWiel commented on server/server_controller.go
> +func (c *ServerController) GetServerCommandWrapper(id int) string {
rename to GetServerStartupCommand

2023-11-06 16:10 UTC, JensvandeWiel commented on server/server_controller.go
> +		return "error getting server command: " + err.Error()
Handle error like other functions

2023-11-06 20:18 UTC, Ivan0348 commented
Can you review again?

2023-11-06 20:38 UTC, JensvandeWiel commented on server/server_controller.go
also return the error to the frontend like (string, error)
look at this for example:
```go
func (c *ServerController) GetServerStatus(id int) (bool, error) {
	server, exists := c.Servers[id]
	if !exists {
		err := fmt.Errorf("error getting server status " + strconv.Itoa(id) + ": server does not exist in map")
		runtime.LogError(c.ctx, err.Error())
		return false, err
	}

	status := server.IsServerRunning()
	return status, nil
}
```

2023-11-06 20:39 UTC, JensvandeWiel requested changes

2023-11-06 20:39 UTC, JensvandeWiel commented on frontend/src/pages/server/Administration.tsx
> +                                            }).catch((err: string) => {
you have a double .catch you can remove one

2023-11-06 20:39 UTC, JensvandeWiel commented on server/server_controller.go
> +func (c *ServerController) GetServerStartupCommand(id int) string {
also return the error to the frontend like (string, error)
look at this for example:
```go
func (c *ServerController) GetServerStatus(id int) (bool, error) {
	server, exists := c.Servers[id]
	if !exists {
		err := fmt.Errorf("error getting server status " + strconv.Itoa(id) + ": server does not exist in map")
		runtime.LogError(c.ctx, err.Error())
		return false, err
	}

	status := server.IsServerRunning()
	return status, nil
}
```

2023-11-07 08:36 UTC, Ivan0348 commented
can you review again?

2023-11-07 08:44 UTC, JensvandeWiel approved these changes
Great job!

2023-11-07 08:45 UTC, merged